name: The Art of Data Visualization
markdown: redcarpet
pygments: true
baseurl: /TheArtOfDataVisualization
#baseurl: ./
description: The Art of Data Visualization
timezone: America/Chicago


# A list of all authors.
authors:
    bakercp:
        role: Instructor
        name: Christopher Baker
        display_name: Christopher Baker
        gravatar: 8f6ac7bc0f5c26b87269d442d5339206
        email: info@christopherbaker.net
        web: http://christopherbaker.net
        twitter: bakercp
        github: bakercp
        bio: Christopher Baker is an Artist.
    garhodes:
        role: Instructor
        name: Alan Rhodes
        display_name: Alan Rhodes
        gravatar: 
        email: garhodes@GARhodes.com
        web: http://garhodes.com/
        twitter: garhodes
        github: garhodes
    qwentl:
        role: Student
        name: Samuel Goldstein
        display_name: Samuel Goldstein
    mperez4:
        role: Student
        name: Miguel Perez
        display_name: Miguel Perez
    amonks:
        role: Student
        name: Andrew Monks
        display_name: Andrew Monks
    hs1399:
        role: Student
        name: hs1399
        display_name: hs1399
    sendtogil:
        role: Student
        name: sendtogil
        display_name: sendtogil
    megrymo:
        role: Student
        name: Meghan Ryan Morris
        display_name: Meghan Ryan Morris
    charmainedacosta:
        role: Student
        name: Charmaine Da Costa
        display_name: Charmaine Da Costa
    megrymo:
        role: Student
        name: Meghan Ryan Morris
        display_name: Meghan Ryan Morris
    jjung429:
        role: Student
        name: jjung429
        display_name: jjung429
    feschr:
        role: Student
        name: feschr
        display_name: feschr
    lucidrod:
        role: Student
        name: lucidrod
        display_name: lucidrod
    yichyu:
        role: Student
        name: yichyu
        display_name: yichyu
    taekhyunkim:
        role: Student
        name: Taek Kim
        display_name: Taek Kim
    kyoungman:
        role: Student
        name: Kristen Youngman
        display_name: Kyoungman
    semishen:
        role: Student
        name: semishen
        display_name: semishen
    jangho84:
        role: Student
        name: Jangho Park
        display_name: Jangho Park

# assets:
#     css:
#         bootstrap: /assets/css/bootstrap.min.css
#         fontawesome: /assets/css/font-awesome.min.css
#     js:
#         jquery: /assets/js/jquery-1.11.0.min.js
#         bootstrap: /assets/js/bootstrap.min.js
#         # d3: //cdnjs.cloudflare.com/ajax/libs/d3/3.4.1/d3.min.js

assets:
    css:
        bootstrap: //netdna.bootstrapcdn.com/bootswatch/3.0.3/readable/bootstrap.min.css
        fontawesome: //netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css
    js:
        jquery: //ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js
        bootstrap: //netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js
        d3: //cdnjs.cloudflare.com/ajax/libs/d3/3.4.1/d3.min.js
