name: The Art of Data Visualization
markdown: redcarpet
pygments: true
baseurl: /TheArtOfDataVisualization
#baseurl: ./
url: https://github.com/SAIC/TheArtOfDataVisualization
description: The Art of Data Visualization
timezone: America/Chicago

